version: '3.8'
services:
  # Django application served by apache
  backend:
    hostname: ${PROJECT_NAME}_backend
    image: backend
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/diseases/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  frontend:
    hostname: ${PROJECT_NAME}_frontend
    image: frontend
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    hostname: ${PROJECT_NAME}_postgres
    image: postgres:14.6
    restart: always  # If the container restarts endlessly and you can't figure out why, change this to 'never'
    environment: 
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  statsd:
    image: graphiteapp/graphite-statsd
    volumes:
    - .conf:/opt/graphite/storage
    - .conf:/opt/graphite/conf
    user: "1000:1000"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    volumes:
    - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/login/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - backend
    ports:
      - ${GRAFANA_WEBSERVER_PORT}:3000
  
  redis:
    hostname: ${PROJECT_NAME}_redis
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local

  grafana-data:
    driver: local
    
  redis-data:
    driver: local