version: '3'
services:
  reverse-proxy:
    hostname: traefik.${HOST}
    image: traefik:v2.9
    network_mode: "host"
    command: 
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.auth:/etc/traefik/traefik.auth
      - ./config/traefik.yml:/etc/traefik/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.rule=Host(`traefik.${HOST}`)
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.entrypoints=web,secure
      - traefik.http.services.reverseproxy_${PROJECT_NAME}.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/traefik.auth
#     - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_STR}
#     - traefik.http.middlewares.auth.basicauth.headerField=X-WebAuth-User
