version: '3'
services:
  reverse-proxy:
    hostname: traefik.${HOST}
    image: traefik:v2.9
    network_mode: "host"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=themichaelreimer@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.auth:/etc/traefik/traefik.auth
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - certs:/etc/ssl/traefik
      - letsencrypt:/letsencrypt/
    labels:
      - traefik.enable=true
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.rule=Host(`traefik.${HOST}`)
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.entrypoints=web,secure
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.tls=${SSL}
      - traefik.http.routers.reverseproxy_${PROJECT_NAME}.tls.certresolver=myresolver
      - traefik.http.services.reverseproxy_${PROJECT_NAME}.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/traefik.auth
#     - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_STR}
#     - traefik.http.middlewares.auth.basicauth.headerField=X-WebAuth-User
      - traefik.http.middlewares.secure-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.secure-redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=secure-redirect
    environment:
      - CLOUDFLARE_EMAIL=${ADMIN_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
volumes:
  certs:

  letsencrypt:
