# Generated by Django 4.2 on 2023-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0003_auto_20210228_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="processed_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
