# Generated by Django 4.2 on 2023-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0004_article_processed_timestamp"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["processed_timestamp"], name="wiki_articl_process_b3df35_idx"),
        ),
    ]
