# Generated by Django 4.2 on 2023-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0005_article_wiki_articl_process_b3df35_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation_text", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="FactType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlexibleValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "single_value",
                    models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
                ),
                ("string_value", models.TextField(blank=True, null=True)),
                (
                    "min_range",
                    models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
                ),
                (
                    "max_range",
                    models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("single", "single value"),
                            ("range", "range value"),
                            ("string", "string value"),
                        ],
                        default="single",
                        max_length=6,
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        choices=[("<", "<"), (">", ">"), ("", ""), ("~", "~")],
                        default="",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="case_fatality_rate",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="causes",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="deaths",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="diagnostic_methods",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="medications",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="mortality_rate",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="preventions",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="risk_factors",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="wikidisease",
            name="treatments",
        ),
        migrations.AddField(
            model_name="article",
            name="link",
            field=models.TextField(default=""),
        ),
        migrations.DeleteModel(
            name="WikiCaseFatalityRate",
        ),
        migrations.DeleteModel(
            name="WikiCause",
        ),
        migrations.DeleteModel(
            name="WikiDeath",
        ),
        migrations.DeleteModel(
            name="WikiDiagnosticMethod",
        ),
        migrations.DeleteModel(
            name="WikiFrequency",
        ),
        migrations.DeleteModel(
            name="WikiMedication",
        ),
        migrations.DeleteModel(
            name="WikiMortalityRate",
        ),
        migrations.DeleteModel(
            name="WikiPrevention",
        ),
        migrations.DeleteModel(
            name="WikiRiskFactor",
        ),
        migrations.DeleteModel(
            name="WikiSpecialty",
        ),
        migrations.DeleteModel(
            name="WikiSymptom",
        ),
        migrations.DeleteModel(
            name="WikiTreatment",
        ),
        migrations.AddField(
            model_name="fact",
            name="disease",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wiki.wikidisease"),
        ),
        migrations.AddField(
            model_name="fact",
            name="fact_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wiki.facttype"),
        ),
        migrations.AddField(
            model_name="fact",
            name="source_article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wiki.article",
            ),
        ),
        migrations.AddField(
            model_name="fact",
            name="value",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wiki.flexiblevalue"),
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(fields=["disease"], name="wiki_fact_disease_9ea3f4_idx"),
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(fields=["fact_type"], name="wiki_fact_fact_ty_8ad9b2_idx"),
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(fields=["disease", "fact_type"], name="wiki_fact_disease_d05527_idx"),
        ),
    ]
