api:
  dashboard: true
  insecure: true

providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

entryPoints:
  web:
    address: ":80"
  secure:
    address: ":443"
    tls:
      domains:
        - main: ${HOST}
          sans: "*.${HOST}"

      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
#  asdf:
#    address: ":8080"

log:
  level: DEBUG

http:
  routers:
    traefik:
      middlewares: "basicauth"
  middlewares:
    basicauth:
      basicAuth:
        removeHeader: true
        users:
          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/

certificatesResolvers:
  myresolver:
    acme:
      #tlschallenge: true
      email: ${ADMIN_EMAIL}
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
