api:
  dashboard: true
  insecure: true

providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

entryPoints:
  web:
    address: ":80"
  secure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: ${HOST}
            sans: "*.${HOST}"
#  asdf:
#    address: ":8080"

log:
  level: DEBUG

http:
  routers:
    traefik:
      middlewares: "basicauth"
  middlewares:
    basicauth:
      basicAuth:
        removeHeader: true
        users:
          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/

certificatesResolvers:
  myresolver:
    acme:
      #tlschallenge: true
      email: ${ADMIN_EMAIL}
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
