# Generated by Django 4.2 on 2023-04-18 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type:ignore

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("link", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_timestamp", models.DateTimeField()),
                (
                    "loaded_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_timestamp", models.DateTimeField()),
                ("file_path", models.TextField()),
                ("link", models.TextField(default="")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="datalake.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["name"], name="datalake_da_name_daac1d_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdata",
            index=models.Index(
                fields=["source", "-processed_timestamp"],
                name="datalake_ra_source__bcdf3d_idx",
            ),
        ),
    ]
