# Generated by Django 4.2 on 2023-04-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalake", "0003_rawdata_datalake_ra_source__13a82d_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="processed_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
