# Generated by Django 4.2 on 2023-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmd", "0003_mortalitydatum_mortalityseries_mortalitysource_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="short_name",
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["name"], name="hmd_country_name_ac32f8_idx"),
        ),
    ]
