# Generated by Django 4.2 on 2023-04-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datalake", "0001_initial"),
        ("hmd", "0004_remove_country_short_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mortalityseries",
            name="source",
        ),
        migrations.AddField(
            model_name="mortalitydatum",
            name="raw_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datalake.rawdata",
            ),
        ),
        migrations.DeleteModel(
            name="MortalitySource",
        ),
    ]
