# Generated by Django 4.2 on 2023-04-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmd", "0005_remove_mortalityseries_source_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mortalityseries",
            name="hmd_mortali_tags_45e22b_idx",
        ),
        migrations.RemoveField(
            model_name="mortalityseries",
            name="age",
        ),
        migrations.RemoveField(
            model_name="mortalityseries",
            name="country",
        ),
        migrations.RemoveField(
            model_name="mortalityseries",
            name="sex",
        ),
        migrations.AddField(
            model_name="mortalitydatum",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="mortalityseries",
            index=models.Index(fields=["tags"], name="hmd_mortali_tags_e55892_idx"),
        ),
    ]
