# Generated by Django 4.2 on 2023-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmd", "0006_remove_mortalityseries_hmd_mortali_tags_45e22b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortalitydatum",
            name="value",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
    ]
