name: Pull Request
run-name: CD ${{github.event.pull_request.number}}
on:
  pull_request:
    types: [ready_for_review, opened, synchronize, closed]

jobs:
  setup:
    runs-on: ['self-hosted', 'cd']
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          clean: 'true'
          submodules: 'false'
          fetch-depth: 1

      - name: "Install Requirements"
        run: |
          pip3 install -r requirements.txt
          cp ~/medistat.env .env

      - name: "Setup Services"
        run: |
          python3 manager.py build
          python3 manager.py up
          python3 manager.py manage migrate

      - name: "Ensure services are healthy"
        run: python3 manager.py check_services

concurrency:
  group: cd_pipeline_${{ github.event.pull_request.number }}
  cancel-in-progress: true